#server:
#  servlet:
#    context-path: /sivo
#
#spring:
#  application:
#    name: Sivo
#
#  datasource:
#    url: jdbc:postgresql://localhost:5433/siicol_db
#    username: siicol_user
#    password: siicol_pass
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#acta:
#  imagenes:
#    base-path: ${SIVO_STORAGE_PATH:D:/archivoSiicol}
#    relative-path: /sivo/actas
#    max-size: 15728640
#    buffer-size: 4096
#
#jwt:
#  secret: e3pLV3tPUUg3KiI1OFYkYj04Sn1pQl5IeTgteWdXRyhfeWU1TmU2UmNMZSM0YFM/VEtNey84TD9NPUs0dFpF
#  expirationMs: 43200
#
#aes:
#  secretKey: QwErTyUiOpAsDfGh

server:
  port: ${PORT:8180}
  servlet:
    context-path: /sivo

spring:
  application:
    name: Sivo

  datasource:
    url: jdbc:oracle:thin:@//172.16.1.203:1521/siicol19_pruebas_pdb.sub12111935041.vcnpruebas.oraclevcn.com
    username: pr
    password: PR-s1C0l-T3st
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

acta:
  imagenes:
    base-path: ${SIVO_STORAGE_PATH:D:/archivoSiicol}
    relative-path: /sivo/actas
    max-size: 15728640
    buffer-size: 4096

jwt:
  secret: e3pLV3tPUUg3KiI1OFYkYj04Sn1pQl5IeTgteWdXRyhfeWU1TmU2UmNMZSM0YFM/VEtNey84TD9NPUs0dFpF
  expirationMs: 43200

aes:
  secretKey: QwErTyUiOpAsDfGh